version: '3.7'
services:
  app:
    build: 
      context: .
      dockerfile: ./system/python/Dockerfile
    container_name: app
    ports:
      - "8000:8000"
    env_file: 
      - .env
    volumes:
      - ./src/app:/usr/src/app
      - ./src/worker:/usr/src/worker

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
  
  kafka:
    build:
      context: .
      dockerfile: ./system/kafka-docker/Dockerfile
    container_name: kafka
    ports:
      - "9092:9092"
    expose:
      - "9093"
    env_file: 
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  kowl:
    image: quay.io/cloudhut/kowl:v1.4.0
    container_name: kowl
    restart: on-failure
    hostname: kowl
    volumes:
      - ./system/kafka-docker/kowl-config.yaml:/etc/kowl/config.yaml
    ports:
      - "8080:8080"
    entrypoint: ./kowl --config.filepath=/etc/kowl/config.yaml
    depends_on:
      - kafka
